### ISSUE TITLE
Add !extends constructor

### ISSUE THREAD

**Issue by albireox** [sdss/sdsstools#7]
Add a PyYAML constructor to base a YAML file on another. For example

```yaml
# file: a.yml
a: 1
b:
  c: 3
  d: 4
```

```yaml
# file: b.yaml
!extends a.yml
b:
  c: 42
```

would be parsed into `{a: 1, b: {c: 42, d: 4}}`.

This would be useful for example for APO/LCO configuration files in which on can be made the template and the other can just extend and modify it.
